apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-dev
  source:
    repoURL: 'https://github.com/Pokepasaj/mockup_v2'
    targetRevision: HEAD
    path: 'sqlite'
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true