apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
spec:
  project: default
  source:
    repoURL: https://github.com/Pokepasaj/mockup_v2
    targetRevision: HEAD
    path: sqlite
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-dev
    syncOptions:
      - CreateNamespace=true
