---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      name: n8n
  template:
    metadata:
      labels:
        name: n8n
    spec:
      containers:
        - name: nginx
          image: eu.gcr.io/topvine-co/nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5678
          env:
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-basic-auth
                  key: user
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-basic-auth
                  key: password
            - name: N8N_SECURE_COOKIE
              value: "false" # Disable secure cookies
            # - name: N8N_HOST
            #   value: "n8n.tpv.k8s"
            # - name: N8N_PROTOCOL
            #   value: "http"
            # - name: N8N_PORT
            #   value: "80"
            #- name: N8N_PROTOCOL
            #  value: "https"
            #- name: N8N_PORT
            #  value: "443"
            - name: VUE_APP_URL_BASE_API
              value: "http://n8n.tpv.k8s/"
            - name: WEBHOOK_TUNNEL_URL
              value: "http://n8n.tpv.k8s/"
      volumes:
        - name: nginx
          configMap:
            name: nginx
